### ISSUE TITLE
Tidy and organize CyborgRobot repo

### ISSUE THREAD

**Issue by A-make** [thentnucyborg/CyborgRobot#29]
### Todo:

Reorganize src packages into high level module folders:
  - [ ] Command: commander (ROS node); CLI, GUI (external) 
  - [ ] Controllers: audio, led-dome, navigation, rosaria, ros-arnl, AriaCoda, rosaria_client etc.
    - [ ] remove packages that are no longer required
  - [ ] Behavior: behavior, event_scheduler, primary_states, controller, CLI, smach, xdot etc.
    - [ ] Evaluate if behavior needs this many nodes

Name changes:
- [ ] cyborg_audio -> controller_audio
- [ ] cyborg_ros_led_dome -> controller_led_dome
- [ ] cyborg_ros_navigation -> controller_navigation
- [ ] cyborg_primary_states -> behavior_primary_states
- [ ] cyborg_eventscheduler -> behavior_eventscheduler
- [ ] cyborg_behavior -> behavior_behaviors
- [ ] cyborg_ros_controller -> behavior_controller
- [ ] cyborg_ros_command -> behavior_CLI

Make new nodes:
- [ ] commander
- [ ] vision

Other:
  - [ ] remove mode-selector?
  - [ ] make (better) coherent node naming convention
  - [ ] put non-ROS packages in "utils" folders
- [x] merge similar nodes
  - [x] merge LED-box and LED-dome
- [ ] remove nodes not used
